(function(){var h={},mt={},c={id:"956adefb0eb473d0cd054107659ab6fd",dm:["fotile.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[{id:"shopurl1",eventType:"onclick"},{id:"shopurl2",eventType:"onclick"}],icon:'',ctrk:true,align:1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:1,vcard:678871,qiao:0,lxb:0,conv:0,med:0,cvcc:{q:/tencent:\/\/|qq\.(com|htm)|kefu|openkf|swt|zoos|53kf|doyoo|looyu|leyu|zixun|chat|talk|openQQ|open_ask|online/i},cvcf:[],apps:''};var p=void 0,q=!0,s=null,w=!1;mt.i={};mt.i.Y=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.i.La=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:p;mt.i.cookieEnabled=navigator.cookieEnabled;mt.i.javaEnabled=navigator.javaEnabled();mt.i.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.i.Oa=(window.screen.width||0)+"x"+(window.screen.height||0);mt.i.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,d,f){var b;f.K&&(b=new Date,b.setTime(b.getTime()+f.K));document.cookie=a+"="+d+(f.domain?"; domain="+f.domain:"")+(f.path?"; path="+f.path:"")+(b?"; expires="+b.toGMTString():"")+(f.Za?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:s};mt.m={};mt.m.L=function(a){return document.getElementById(a)};mt.m.xa=function(a){var d;for(d="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return s};
(mt.m.R=function(){function a(){if(!a.B){a.B=q;for(var d=0,e=b.length;d<e;d++)b[d]()}}function d(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(d,1);return}a()}var f=w,b=[],e;document.addEventListener?e=function(){document.removeEventListener("DOMContentLoaded",e,w);a()}:document.attachEvent&&(e=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",e),a())});(function(){if(!f)if(f=q,"complete"===document.readyState)a.B=q;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
e,w),window.addEventListener("load",a,w);else if(document.attachEvent){document.attachEvent("onreadystatechange",e);window.attachEvent("onload",a);var b=w;try{b=window.frameElement==s}catch(m){}document.documentElement.doScroll&&b&&d()}})();return function(d){a.B?d():b.push(d)}}()).B=w;mt.event={};mt.event.c=function(a,d,f){a.attachEvent?a.attachEvent("on"+d,function(b){f.call(a,b)}):a.addEventListener&&a.addEventListener(d,f,w)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=w};mt.k={};mt.k.parse=function(){return(new Function('return (" + source + ")'))()};
mt.k.stringify=function(){function a(b){/["\\\x00-\x1f]/.test(b)&&(b=b.replace(/["\\\x00-\x1f]/g,function(b){var a=f[b];if(a)return a;a=b.charCodeAt();return"\\u00"+Math.floor(a/16).toString(16)+(a%16).toString(16)}));return'"'+b+'"'}function d(b){return 10>b?"0"+b:b}var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(b){switch(typeof b){case "undefined":return"undefined";case "number":return isFinite(b)?String(b):"null";case "string":return a(b);case "boolean":return String(b);
default:if(b===s)return"null";if(b instanceof Array){var e=["["],f=b.length,m,g,k;for(g=0;g<f;g++)switch(k=b[g],typeof k){case "undefined":case "function":case "unknown":break;default:m&&e.push(","),e.push(mt.k.stringify(k)),m=1}e.push("]");return e.join("")}if(b instanceof Date)return'"'+b.getFullYear()+"-"+d(b.getMonth()+1)+"-"+d(b.getDate())+"T"+d(b.getHours())+":"+d(b.getMinutes())+":"+d(b.getSeconds())+'"';m=["{"];g=mt.k.stringify;for(f in b)if(Object.prototype.hasOwnProperty.call(b,f))switch(k=
b[f],typeof k){case "undefined":case "unknown":case "function":break;default:e&&m.push(","),e=1,m.push(g(f)+":"+g(k))}m.push("}");return m.join("")}}}();mt.lang={};mt.lang.d=function(a,d){return"[object "+d+"]"==={}.toString.call(a)};mt.lang.Wa=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.Ya=function(a){return mt.lang.d(a,"String")};mt.localStorage={};
mt.localStorage.H=function(){if(!mt.localStorage.g)try{mt.localStorage.g=document.createElement("input"),mt.localStorage.g.type="hidden",mt.localStorage.g.style.display="none",mt.localStorage.g.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.g)}catch(a){return w}return q};
mt.localStorage.set=function(a,d,f){var b=new Date;b.setTime(b.getTime()+f||31536E6);try{window.localStorage?(d=b.getTime()+"|"+d,window.localStorage.setItem(a,d)):mt.localStorage.H()&&(mt.localStorage.g.expires=b.toUTCString(),mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.setAttribute(a,d),mt.localStorage.g.save(document.location.hostname))}catch(e){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var d=a.indexOf("|"),f=a.substring(0,d)-0;if(f&&f>(new Date).getTime())return a.substring(d+1)}}else if(mt.localStorage.H())try{return mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.getAttribute(a)}catch(b){}return s};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.H())try{mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.removeAttribute(a),mt.localStorage.g.save(document.location.hostname)}catch(d){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,d){if(window.sessionStorage)try{window.sessionStorage.setItem(a,d)}catch(f){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):s};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.ba={};mt.ba.log=function(a,d){var f=new Image,b="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[b]=f;f.onload=f.onerror=f.onabort=function(){f.onload=f.onerror=f.onabort=s;f=window[b]=s;d&&d(a)};f.src=a};mt.G={};
mt.G.Da=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var d=navigator.plugins["Shockwave Flash"];d&&d.description&&(a=d.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=d.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(f){}return a};
mt.G.qa=function(a,d,f,b,e){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+f+'" height="'+b+'"><param name="movie" value="'+d+'" /><param name="flashvars" value="'+(e||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+f+'" height="'+b+'" src="'+d+'" flashvars="'+(e||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.j=function(a,d){var f=a.match(RegExp("(^|&|\\?|#)("+d+")=([^&#]*)(&|$|#)",""));return f?f[3]:s};mt.url.Va=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:s};mt.url.Aa=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):s};mt.url.W=function(a){return(a=mt.url.Aa(a))?a.replace(/:\d+$/,""):a};mt.url.Ua=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):s};
(function(){function a(){for(var a=w,f=document.getElementsByTagName("script"),b=f.length,b=100<b?100:b,e=0;e<b;e++){var l=f[e].src;if(l&&0===l.indexOf("https://hm.baidu.com/h")){a=q;break}}return a}return h.wa=a})();var y=h.wa;
h.h={Ka:"http://tongji.baidu.com/hm-web/welcome/ico",Q:"hm.baidu.com/hm.gif",ha:"baidu.com",Ha:"hmmd",Ia:"hmpl",Ga:"hmkw",Ea:"hmci",Ja:"hmsr",Fa:"hmcu",s:0,l:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",C:y()||"https:"===document.location.protocol?"https:":"http:",Xa:0,oa:6E5,pa:10,T:1024,na:1,r:2147483647,ca:"bs cc cf ci ck cl cm cp cu cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api u tt".split(" ")};
(function(){var a={p:{},c:function(a,f){this.p[a]=this.p[a]||[];this.p[a].push(f)},z:function(a,f){this.p[a]=this.p[a]||[];for(var b=this.p[a].length,e=0;e<b;e++)this.p[a][e](f)}};return h.o=a})();
(function(){function a(a,b){var e=document.createElement("script");e.charset="utf-8";d.d(b,"Function")&&(e.readyState?e.onreadystatechange=function(){if("loaded"===e.readyState||"complete"===e.readyState)e.onreadystatechange=s,b()}:e.onload=function(){b()});e.src=a;var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(e,l)}var d=mt.lang;return h.load=a})();
(function(){function a(){var a="";h.b.a.nv?(a=encodeURIComponent(document.referrer),window.sessionStorage?f.set("Hm_from_"+c.id,a):d.set("Hm_from_"+c.id,a,864E5)):a=(window.sessionStorage?f.get("Hm_from_"+c.id):d.get("Hm_from_"+c.id))||"";return a}var d=mt.localStorage,f=mt.sessionStorage;return h.U=a})();
(function(){var a=h.h,d=mt.G,f={init:function(){if(""!==c.icon){var b;b=c.icon.split("|");var e=a.Ka+"?s="+c.id,f=("http:"==a.protocol?"http://eiv":"https://bs")+".baidu.com"+b[0]+"."+b[1];switch(b[1]){case "swf":b=d.qa("HolmesIcon"+a.l,f,b[2],b[3],"s="+e);break;case "gif":b='<a href="'+e+'" target="_blank"><img border="0" src="'+f+'" width="'+b[2]+'" height="'+b[3]+'"></a>';break;default:b='<a href="'+e+'" target="_blank">'+b[0]+"</a>"}document.write(b)}}};h.o.c("pv-b",f.init);return f})();
(function(){var a=mt.m,d=mt.event,f={ea:function(){d.c(document,"click",f.ta());for(var b=c.etrk.length,e=0;e<b;e++){var l=c.etrk[e],m=a.L(decodeURIComponent(l.id));m&&d.c(m,l.eventType,f.J())}},J:function(){return function(a){(a.target||a.srcElement).setAttribute("HM_fix",a.clientX+":"+a.clientY);h.b.a.et=1;h.b.a.ep="{id:"+this.id+",eventType:"+a.type+"}";h.b.f()}},ta:function(){return function(a){var e=a.target||a.srcElement;if(e){var f=e.getAttribute("HM_fix"),d=a.clientX+":"+a.clientY;if(f&&f==
d)e.removeAttribute("HM_fix");else if(f=c.etrk.length,0<f){for(d={};e&&e!=document.body;)e.id&&(d[e.id]=""),e=e.parentNode;for(e=0;e<f;e++){var g=decodeURIComponent(c.etrk[e].id);d.hasOwnProperty(g)&&(h.b.a.et=1,h.b.a.ep="{id:"+g+",eventType:"+a.type+"}",h.b.f())}}}}}};h.o.c("pv-b",f.ea);return f})();
(function(){var a=mt.m,d=mt.event,f=mt.i,b=h.h,e=[],l={da:function(){c.ctrk&&(d.c(document,"mouseup",l.ma()),d.c(window,"unload",function(){l.D()}),setInterval(function(){l.D()},b.oa))},ma:function(){return function(a){a=l.ya(a);if(""!==a){var f=(b.C+"//"+b.Q+"?"+h.b.aa().replace(/ep=[^&]*/,"ep="+encodeURIComponent("["+a+"]"))).length;f+(b.r+"").length>b.T||(f+encodeURIComponent(e.join(",")+(e.length?",":"")).length+(b.r+"").length>b.T&&l.D(),e.push(a),(e.length>=b.pa||/t:a/.test(a))&&l.D())}}},ya:function(d){if(0===
b.na){var e=d.target||d.srcElement,k=e.tagName.toLowerCase();if("embed"==k||"object"==k)return""}f.Y?(e=Math.max(document.documentElement.scrollTop,document.body.scrollTop),k=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),k=d.clientX+k,e=d.clientY+e):(k=d.pageX,e=d.pageY);var n=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:k-=n/2;break;case 2:k-=n}k="{x:"+k+",y:"+e+",";e=d.target||d.srcElement;return k=(d="a"==e.tagName.toLowerCase()?
e:a.xa(e))?k+("t:a,u:"+encodeURIComponent(d.href)+"}"):k+"t:b}"},D:function(){0!==e.length&&(h.b.a.et=2,h.b.a.ep="["+e.join(",")+"]",h.b.f(),e=[])}};h.o.c("pv-b",l.da);return l})();
(function(){var a=mt.m,d=h.h,f=h.load,b=h.U;h.o.c("pv-b",function(){c.rec&&a.R(function(){for(var e=0,l=c.rp.length;e<l;e++){var m=c.rp[e][0],g=c.rp[e][1],k=a.L("hm_t_"+m);if(g&&!(2==g&&!k||k&&""!==k.innerHTML))k="",k=Math.round(Math.random()*d.r),k=4==g?"http://crs.baidu.com/hl.js?"+["siteId="+c.id,"planId="+m,"rnd="+k].join("&"):"http://crs.baidu.com/t.js?"+["siteId="+c.id,"planId="+m,"from="+b(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
k].join("&"),f(k)}})})})();(function(){var a=h.h,d=h.load,f=h.U;h.o.c("pv-b",function(){if(c.trust&&c.vcard){var b="https://trust.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+f(),"rnd="+Math.round(Math.random()*a.r),"hm=1"].join("&");d(b)}})})();
(function(){function a(){function a(b){function k(){}for(var f=q,l=0,u=0,r=s,t=s,z=b.length,x=0,A=s,l=0;l<z;l++)if(r=b[l],r.chromeVer===m){f=q;t=r.tests;x=t.length;for(u=0;u<x;u++)if(k=d[t[u].name],k()!==t[u].expect){f=w;break}if(x&&f){A={name:"360browser",type:r.type,version:r.ver};break}}return A}var b=[];b.push({ver:"8.3",type:"fast",tests:[{name:"seamlessiframe",expect:1}],chromeVer:"42"});var d={pointerevents:function(){return"maxTouchPoints"in window.navigator?1:"msMaxTouchPoints"in window.navigator||
"mozMaxTouchPoints"in window.navigator||"webkitMaxTouchPoints"in window.navigator?9:0},webgl3D:function(){for(var a="webgl ms-webgl experimental-webgl moz-webgl opera-3d webkit-3d ms-3d 3d".split(" "),k=a.length,b="",d=document.createElement("canvas"),f=w,e=0;e<k;e++)try{if(d.getContext(a[e])){f=q;b=a[e];break}}catch(t){}return f?"webgl"===b?1:9:0},seamlessiframe:function(){return"seamless"in document.createElement("iframe")?1:0},speechsynthesis:function(){return"speechSynthesis"in window?1:"webkitSpeechSynthesis"in
window||"mozSpeechSynthesis"in window||"oSpeechSynthesis"in window||"msSpeechSynthesis"in window?9:0}},l=s,m=function(){var a=navigator.userAgent.toLowerCase().match(/chrome\/(\d+)/i);return a?a[1]:"-1"}();"-1"!==m&&(l=a(b));return l}var d=function(){var d=navigator.userAgent.toLowerCase();if(0<=d.indexOf("chrome")){var d=(d=d.match(/chrome\/(\d+)/))?d[1]:-1,b=window.document,e="track"in b.createElement("track"),b="scoped"in b.createElement("style"),l="v8Locale"in window,m=document.createElement("canvas"),
g="seamless"in document.createElement("iframe"),k=w;try{m.getContext("webgl")&&(k=q)}catch(n){}if(m=a())return"fast"===m.type?7:1;if(!k&&"31"===d)return 1;if(!(g=(g||!k)&&"38"===d))if(g=e)if(g=!b)if(g=!l){var v;a:{g=window.navigator.mimeTypes;for(v in g)if("application/vnd.chromium.remoting-viewer"===g[v].type){v=q;break a}v=w}g=!v&&46>+d}if(g)return 7;if(e&&b&&l)return 1}return-1}();return h.ka=d})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.I.Ba()+","+h.I.za();h.b.f()}}function d(){clearTimeout(A);var a;z&&(a="visible"==document[z]);x&&(a=!document[x]);g="undefined"==typeof a?q:a;if((!m||!k)&&g&&n)t=q,u=+new Date;else if(m&&k&&(!g||!n))t=w,r+=+new Date-u;m=g;k=n;A=setTimeout(d,100)}function f(a){var k=document,b="";if(a in k)b=a;else for(var d=["webkit","ms","moz","o"],e=0;e<d.length;e++){var f=d[e]+a.charAt(0).toUpperCase()+a.slice(1);if(f in k){b=
f;break}}return b}function b(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))n="focus"==a.type||"focusin"==a.type?q:w,d()}var e=mt.event,l=h.o,m=q,g=q,k=q,n=q,v=+new Date,u=v,r=0,t=q,z=f("visibilityState"),x=f("hidden"),A;d();(function(){var a=z.replace(/[vV]isibilityState/,"visibilitychange");e.c(document,a,d);e.c(window,"pageshow",d);e.c(window,"pagehide",d);"object"==typeof document.onfocusin?(e.c(document,"focusin",b),e.c(document,"focusout",b)):(e.c(window,"focus",b),
e.c(window,"blur",b))})();h.I={Ba:function(){return+new Date-v},za:function(){return t?+new Date-u+r:r}};l.c("pv-b",function(){e.c(window,"unload",a())});return h.I})();
(function(){var a=mt.lang,d=h.h,f=h.load,b={Ma:function(b){if((window._dxt===p||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.b){var l=h.b.M();f([d.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(l)].join(""),b)}},Ta:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.ra=b})();
(function(){function a(k){for(var b in k)if({}.hasOwnProperty.call(k,b)){var d=k[b];f.d(d,"Object")||f.d(d,"Array")?a(d):k[b]=String(d)}}function d(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a}var f=mt.lang,b=mt.k,e=h.h,l=h.o,m=h.ra,g={w:[],F:0,Z:w,init:function(){g.e=0;l.c("pv-b",function(){g.sa();g.ua()});l.c("pv-d",g.va);l.c("stag-b",function(){h.b.a.api=g.e||g.F?g.e+"_"+g.F:""});l.c("stag-d",function(){h.b.a.api=0;g.e=0;g.F=0})},sa:function(){var a=window._hmt||
[];if(!a||f.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,k=0;k<arguments.length;k++){var b=arguments[k];f.d(b,"Array")&&(a.cmd[a.id].push(b),"_setAccount"===b[0]&&(1<b.length&&/^[0-9a-f]{32}$/.test(b[1]))&&(b=b[1],a.id=b,a.cmd[b]=a.cmd[b]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},ua:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,e=0,f=b.length;e<f;e++){var t=b[e];
d.test(t[0])?g.w.push(t):g.P(t)}a.cmd[c.id]={push:g.P}},va:function(){if(0<g.w.length)for(var a=0,b=g.w.length;a<b;a++)g.P(g.w[a]);g.w=s},P:function(a){var b=a[0];if(g.hasOwnProperty(b)&&f.d(g[b],"Function"))g[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(g.e|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],w===a||q===a))g.e|=2,h.b.X=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){g.e|=4;h.b.a.et=0;h.b.a.ep="";h.b.N?(h.b.a.nv=0,h.b.a.st=
4):h.b.N=q;var b=h.b.a.u,d=h.b.a.su;h.b.a.u=e.protocol+"//"+document.location.host+a[1];g.Z||(h.b.a.su=document.location.href);h.b.f();h.b.a.u=b;h.b.a.su=d}},_trackEvent:function(a){2<a.length&&(g.e|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=d(a[1])+"*"+d(a[2])+(a[3]?"*"+d(a[3]):"")+(a[4]?"*"+d(a[4]):""),h.b.f())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],e=a[4]||3;if(0<b&&6>b&&0<e&&4>e){g.F++;for(var f=(h.b.a.cv||"*").split("!"),r=f.length;r<b-1;r++)f.push("*");f[b-1]=e+"*"+d(a[2])+
"*"+d(a[3]);h.b.a.cv=f.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.Na("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"===a[1].charAt(0)?e.protocol+"//"+window.location.host+a[1]:a[1],g.Z=q)},_trackOrder:function(d){d=d[1];f.d(d,"Object")&&(a(d),g.e|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=b.stringify(d),h.b.f())},_trackMobConv:function(a){if(a={webim:1,
tel:2,map:3,sms:4,callback:5,share:6}[a[1]])g.e|=32,h.b.a.et=93,h.b.a.ep=a,h.b.f()},_trackRTPageview:function(d){d=d[1];f.d(d,"Object")&&(a(d),d=b.stringify(d),512>=encodeURIComponent(d).length&&(g.e|=64,h.b.a.rt=d))},_trackRTEvent:function(d){d=d[1];if(f.d(d,"Object")){a(d);d=encodeURIComponent(b.stringify(d));var l=function(a){var b=h.b.a.rt;g.e|=128;h.b.a.et=90;h.b.a.rt=a;h.b.f();h.b.a.rt=b},m=d.length;if(900>=m)l.call(this,d);else for(var m=Math.ceil(m/900),u="block|"+Math.round(Math.random()*
e.r).toString(16)+"|"+m+"|",r=[],t=0;t<m;t++)r.push(t),r.push(d.substring(900*t,900*t+900)),l.call(this,u+r.join("|")),r=[]}},_setUserId:function(a){a=a[1];m.Ma();m.Ta(a)}};g.init();h.ia=g;return h.ia})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=q,this.a={},this.X=q,this.N=w,this.init())}var d=mt.url,f=mt.ba,b=mt.G,e=mt.lang,l=mt.cookie,m=mt.i,g=mt.localStorage,k=mt.sessionStorage,n=h.h,v=h.ka,u=h.o;a.prototype={O:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},$:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},A:function(a){for(var b=0;b<c.dm.length;b++)if(-1<
c.dm[b].indexOf("/")){if(this.$(a,c.dm[b]))return q}else{var e=d.W(a);if(e&&this.O(e,c.dm[b]))return q}return w},M:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.O(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},V:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.$(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},Ca:function(){if(!document.referrer)return n.l-n.s>c.vdur?1:4;var a=
w;this.A(document.referrer)&&this.A(document.location.href)?a=q:(a=d.W(document.referrer),a=this.O(a||"",document.location.hostname));return a?n.l-n.s>c.vdur?1:4:3},getData:function(a){try{return l.get(a)||k.get(a)||g.get(a)}catch(b){}},setData:function(a,b,d){try{l.set(a,b,{domain:this.M(),path:this.V(),K:d}),d?g.set(a,b,d):k.set(a,b)}catch(e){}},Na:function(a){try{l.set(a,"",{domain:this.M(),path:this.V(),K:-1}),k.remove(a),g.remove(a)}catch(b){}},Ra:function(){var a,b,d,e,f;n.s=this.getData("Hm_lpvt_"+
c.id)||0;13===n.s.length&&(n.s=Math.round(n.s/1E3));b=this.Ca();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<n.l-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(n.l);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=n.l,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,n.l);d=n.l===this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.A(document.location.href)&&
(""===document.referrer||this.A(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=e;this.a.lv=f},aa:function(){for(var a=[],b=this.a.et,d=0,e=n.ca.length;d<e;d++){var f=n.ca[d],g=this.a[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},Sa:function(){this.Ra();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=
m.Oa;this.a.cl=m.colorDepth+"-bit";this.a.ln=String(m.language).toLowerCase();this.a.ja=m.javaEnabled?1:0;this.a.ck=m.cookieEnabled?1:0;this.a.bs=v;this.a.lo="number"===typeof _bdhm_top?1:0;this.a.fl=b.Da();this.a.v="1.2.10";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.a.tt=document.title||"";var a=document.location.href;this.a.cm=d.j(a,n.Ha)||"";this.a.cp=d.j(a,n.Ia)||"";this.a.cw=d.j(a,n.Ga)||"";this.a.ci=d.j(a,n.Ea)||"";this.a.cf=d.j(a,n.Ja)||"";this.a.cu=d.j(a,n.Fa)||""},
init:function(){try{this.Sa(),0===this.a.nv?this.Qa():this.S(".*"),h.b=this,this.la(),u.z("pv-b"),this.Pa()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));f.log(n.C+"//"+n.Q+"?"+b.join("&"))}},Pa:function(){function a(){u.z("pv-d")}this.X?(this.N=q,this.a.et=0,this.a.ep="",this.f(a)):a()},f:function(a){var b=this;b.a.rnd=Math.round(Math.random()*n.r);u.z("stag-b");var d=n.C+
"//"+n.Q+"?"+b.aa();u.z("stag-d");b.ga(d);f.log(d,function(d){b.S(d);e.d(a,"Function")&&a.call(b)})},la:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),e=-1<document.referrer.indexOf(n.ha),f=d.j(a,"jn"),g=/^heatlink$|^select$/.test(f);a&&(b.test(a)&&e&&g)&&(this.a.rnd=Math.round(Math.random()*n.r),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",n.protocol+"//"+c.js+f+".js?"+this.a.rnd),f=document.getElementsByTagName("script")[0],
f.parentNode.insertBefore(a,f))},ga:function(a){var b=k.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");k.set("Hm_unsent_"+c.id,b)},S:function(a){var b=k.get("Hm_unsent_"+c.id)||"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),a=RegExp(a.replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),(b=b.replace(a,"").replace(/,$/,""))?k.set("Hm_unsent_"+c.id,b):k.remove("Hm_unsent_"+c.id))},
Qa:function(){var a=this,b=k.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),d=function(b){f.log(n.C+"//"+decodeURIComponent(b),function(b){a.S(b)})},e=0,g=b.length;e<g;e++)d(b[e])}};return new a})();var B=h.h,C=h.load;if(c.apps){var D=[B.protocol,"//ers.baidu.com/app/s.js?"];D.push(c.apps);C(D.join(""))}var E=h.h,F=h.load;if(c.conv&&"http:"===E.protocol){var G=["http://page.baidu.com/conversion_js.php?sid="];G.push(c.conv);F(G.join(""))}var H=h.h,I=h.load;
c.lxb&&I([H.protocol,"//lxbjs.baidu.com/lxb.js?sid=",c.lxb].join(""));var J=h.load,K=h.h.protocol;if(c.qiao){for(var L=[K+"//goutong.baidu.com/site/"],M=c.id,N=5381,O=M.length,P=0;P<O;P++)N=(33*N+Number(M.charCodeAt(P)))%4294967296;2147483648<N&&(N-=2147483648);L.push(N%1E3+"/");L.push(c.id+"/b.js");L.push("?siteId="+c.qiao);J(L.join(""))}
(function(){var a=mt.m,d=mt.event,f=mt.url,b=mt.k;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.b){var e=+new Date,l=function(a){var b=performance.timing,d=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:d,end:a,value:0<a-d?a-d:0}},m=s;a.R(function(){m=+new Date});var g=function(){var a,d,g;g=l("navigation");d=l("request");g={netAll:d.start-g.start,netDns:l("domainLookup").value,netTcp:l("connect").value,srv:l("response").start-d.start,dom:performance.timing.domInteractive-
performance.timing.fetchStart,loadEvent:l("loadEvent").end-g.start};a=document.referrer;var k=a.match(/^(http[s]?:\/\/)?([^\/]+)(.*)/)||[],t=s;d=s;if("www.baidu.com"===k[2]||"m.baidu.com"===k[2])t=f.j(a,"qid"),d=f.j(a,"click_t");a=t;g.qid=a!=s?a:"";d!=s?(g.bdDom=m?m-d:0,g.bdRun=e-d,g.bdDef=l("navigation").start-d):(g.bdDom=0,g.bdRun=0,g.bdDef=0);h.b.a.et=87;h.b.a.ep=b.stringify(g);h.b.f()};d.c(window,"load",function(){setTimeout(g,500)})}}catch(k){}})();
(function(){var a=mt.i,d=mt.lang,f=mt.event,b=mt.k;if("undefined"!==typeof h.b&&(c.med||(!a.Y||7<a.La)&&c.cvcc)){var e,l,m,g,k=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},n=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===w)return w},v=function(a,f){var g={};g.n=e;g.t="clk";g.v=a;if(f){var k=f.getAttribute("href"),l=f.getAttribute("onclick")?""+f.getAttribute("onclick"):s,n=f.getAttribute("id")||"";m.test(k)?(g.sn="mediate",
g.snv=k):d.d(l,"String")&&m.test(l)&&(g.sn="wrap",g.snv=l);g.id=n}h.b.a.et=86;h.b.a.ep=b.stringify(g);h.b.f();for(g=+new Date;400>=+new Date-g;);};if(c.med)l="/zoosnet",e="swt",m=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,g={click:function(){for(var a=[],b=k(document.getElementsByTagName("a")),b=[].concat.apply(b,k(document.getElementsByTagName("area"))),b=[].concat.apply(b,k(document.getElementsByTagName("img"))),d,e,f=0,g=b.length;f<g;f++)d=b[f],e=d.getAttribute("onclick"),
d=d.getAttribute("href"),(m.test(e)||m.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){l="/other-comm";e="other";m=c.cvcc.q||p;var u=c.cvcc.id||p;g={click:function(){for(var a=[],b=k(document.getElementsByTagName("a")),b=[].concat.apply(b,k(document.getElementsByTagName("area"))),b=[].concat.apply(b,k(document.getElementsByTagName("img"))),d,e,f,g=0,l=b.length;g<l;g++)d=b[g],m!==p?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),u?(d=d.getAttribute("id"),(m.test(e)||m.test(f)||u.test(d))&&
a.push(b[g])):(m.test(e)||m.test(f))&&a.push(b[g])):u!==p&&(d=d.getAttribute("id"),u.test(d)&&a.push(b[g]));return a}}}if("undefined"!==typeof g&&"undefined"!==typeof m){var r;l+=/\/$/.test(l)?"":"/";var t=function(a,b){if(r===b)return v(l+a,b),w;if(d.d(b,"Array")||d.d(b,"NodeList"))for(var e=0,f=b.length;e<f;e++)if(r===b[e])return v(l+a+"/"+(e+1),b[e]),w};f.c(document,"mousedown",function(a){a=a||window.event;r=a.target||a.srcElement;var b={};for(n(g,function(a,e){b[a]=d.d(e,"Function")?e():document.getElementById(e)});r&&
r!==document&&n(b,t)!==w;)r=r.parentNode})}}})();(function(){var a=mt.m,d=mt.lang,f=mt.event,b=mt.k;if("undefined"!==typeof h.b&&d.d(c.cvcf,"Array")&&0<c.cvcf.length){var e={fa:function(){for(var b=c.cvcf.length,d,g=0;g<b;g++)(d=a.L(decodeURIComponent(c.cvcf[g])))&&f.c(d,"click",e.J())},J:function(){return function(){h.b.a.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.b.a.ep=b.stringify(a);h.b.f()}}};a.R(function(){e.fa()})}})();
(function(){var a=mt.event,d=mt.k;if(c.med&&"undefined"!==typeof h.b){var f=+new Date,b={n:"anti",sb:0,kb:0,clk:0},e=function(){h.b.a.et=86;h.b.a.ep=d.stringify(b);h.b.f()};a.c(document,"click",function(){b.clk++});a.c(document,"keyup",function(){b.kb=1});a.c(window,"scroll",function(){b.sb++});a.c(window,"unload",function(){b.t=+new Date-f;e()});a.c(window,"load",function(){setTimeout(e,5E3)})}})();})();
